#!/bin/bash
#########################################################
# amzlinux jump host for Windows Desktop
# installs system tools for troubleshooting
#########################################################
sudo hostnamectl set-hostname ${agent_machine_name}
#########################################################
# teleport installation 
#########################################################
# installs teleport enterprise edition 
# update for versions >17.3 
curl "https://${domain}/scripts/install.sh" | sudo bash
# Teleport does not allow periods in windows names
WINDOWS_HOST_NAME=$(echo "${windows_internal_dns}" | awk -F. '{print $1}')
#########################################################
# teleport configuration
#########################################################
echo ${token} > /tmp/token

sudo cat << EOF > /etc/teleport.yaml
version: v3
teleport:
  data_dir: "/var/lib/teleport"
  auth_token: /tmp/token
  proxy_server: ${domain}:443
  log:
    output: stderr
    severity: INFO
    format:
      output: json
app_service:
  enabled: false
auth_service:
  enabled: false
db_service:
  enabled: false
discovery_service:
  enabled: true
kubernetes_service:
  enabled: false
proxy_service:
  enabled: false
ssh_service:
  enabled: true
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  labels:
    ${teleport_ssh_label}
    cloud: aws
    os: amz-lin
  enhanced_recording:
    enabled: ${ssh_enhanced_recording_bool}
windows_desktop_service:
  enabled: yes
  show_desktop_wallpaper: true
  static_hosts:
  - name: $WINDOWS_HOST_NAME
    ad: false
    addr: ${windows_internal_dns}
    labels:
      ${teleport_windows_label}
      cloud: aws
      os: windows
EOF
# Sets teleport service to start at boot and brings it up
systemctl enable teleport;
systemctl restart teleport;
