#!/bin/bash
#########################################################
# package installs
#########################################################
sudo hostnamectl set-hostname "mysql"
sudo apt update && sudo apt upgrade -y 
sudo apt install -y mariadb-server mariadb-client jq
sudo systemctl enable mariadb
sudo systemctl start mariadb
sudo mysql_secure_installation << EOF

y
n
y
y
y
y
EOF
########################################################
## teleport installation 
#########################################################
curl https://goteleport.com/static/install.sh | bash -s "${major}" "enterprise"
#########################################################
## teleport configuration
#########################################################
sudo cat <<-EOF > /etc/teleport.yaml
version: v3
teleport:
  data_dir: "/var/lib/teleport"
  proxy_server: "${domain}:443"
  auth_token: "${token}"
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
db_service:
  enabled: true
  resources:
   - labels:
       "tier": "dev"
auth_service:
  enabled: "no"
ssh_service:
  enabled: "true"
  labels:
    tier: dev
proxy_service:
  enabled: "no"
app_service:
  enabled: "no"
EOF

#########################################################
## mariaDB/mysql teleport configuration
#########################################################
# cert installation 
sudo mkdir -p /etc/mysql/ssl
sudo echo "${ca}" > /etc/mysql/ssl/server.cas
sudo echo "${tele_ca}" >> /etc/mysql/ssl/server.cas
sudo echo "${cert}" > /etc/mysql/ssl/server.crt
sudo echo "${key}" > /etc/mysql/ssl/server.key
# mysql config 
sudo cat << EOF > /etc/mysql/conf.d/mysql.cnf
[mariadb]
require_secure_transport=ON
ssl-ca=/etc/mysql/ssl/server.cas
ssl-cert=/etc/mysql/ssl/server.crt
ssl-key=/etc/mysql/ssl/server.key

log_error=/var/log/mysql/mysqld.log
EOF
sudo mysql -u root -e "CREATE USER 'writer'@'%' REQUIRE SUBJECT '/CN=writer';"
sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'writer'@'%';"
sudo mysql -u root -e "CREATE USER 'reader'@'%' REQUIRE SUBJECT '/CN=reader';"
sudo mysql -u root -e "GRANT SELECT ON *.* TO 'reader'@`%`;"
sudo mysql -u root -e "GRANT SHOW VIEW ON *.* TO 'reader'@`%`"
sudo mysql -u root -e "FLUSH PRIVILEGES;"
sudo systemctl restart mariadb
systemctl enable teleport
systemctl restart teleport
#########################################################