#!/bin/bash
#########################################################
# package installs
#########################################################
sudo apt update && sudo apt upgrade -y 
sudo apt install -y mariadb-server mariadb-client net-tools
sudo systemctl enable mariadb
sudo systemctl start mariadb
sudo mysql_secure_installation << EOF

y
n
y
y
y
y
EOF
########################################################
## teleport installation ##needs work
#########################################################
## ENT Edition
sudo curl https://apt.releases.teleport.dev/gpg -o /usr/share/keyrings/teleport-archive-keyring.asc
source /etc/os-release
echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] \
https://apt.releases.teleport.dev/$${ID?} $${VERSION_CODENAME?} stable/v14" \
| sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null
sudo apt-get update
sudo apt-get install teleport-ent
echo ${token} > /var/lib/teleport/token
#########################################################
## teleport configuration
#########################################################
sudo cat <<-EOF > /etc/teleport.yaml
version: v3
teleport:
  data_dir: "/var/lib/teleport"
  proxy_server: "teleport.chrisdlg.com:443"
  auth_token: "/var/lib/teleport/token"
  log:
    output: stderr
    severity: INFO
    format:
      output: text
db_service:
  enabled: true
  databases:
  - name: "mysqldb"
    protocol: "mysql"
    uri: "localhost:3306"
    static_labels:
      "environment": "stage"
      "os": "ubuntu"
      "cloud": "aws"
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  labels:
    environment: stage
    os: ubuntu
    cloud: aws
  enhanced_recording:
    enabled: true
proxy_service:
  enabled: "no"
app_service:
  enabled: "no"
EOF
systemctl enable teleport
systemctl restart teleport
#########################################################
## mariaDB/mysql teleport configuration
#########################################################
sudo mkdir -p /etc/mysql/ssl
sudo touch /etc/mysql/ssl/server.cas
sudo touch /etc/mysql/ssl/server.crt
sudo touch /etc/mysql/ssl/server.key
# Quoting the variable variable is needed here. Otherwise echo will paste each line of the variable into STDIN
sudo echo "${sqlcas}" > /etc/mysql/ssl/server.cas
sudo echo "${sqlcrt}" > /etc/mysql/ssl/server.crt
sudo echo "${sqlkey}" > /etc/mysql/ssl/server.key
sudo cat << EOF > /etc/mysql/conf.d/mysql.cnf
[mariadb]
require_secure_transport=ON
ssl-ca=/etc/mysql/ssl/server.cas
ssl-cert=/etc/mysql/ssl/server.crt
ssl-key=/etc/mysql/ssl/server.key

log_error=/var/log/mysql/mysqld.log
EOF
sudo mysql -u root -e "CREATE USER 'alice'@'%' REQUIRE SUBJECT '/CN=alice';"
sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'alice'@'%';"
sudo mysql -u root -e "CREATE USER 'bob'@'%' REQUIRE SUBJECT '/CN=bob';"
sudo mysql -u root -e "GRANT SELECT ON *.* TO 'bob'@`%`;"
sudo mysql -u root -e "GRANT SHOW VIEW ON *.* TO 'bob'@`%`"
sudo mysql -u root -e "FLUSH PRIVILEGES;"
sudo systemctl restart mariadb
#########################################################