#! /bin/bash
# teleport installation 
curl https://deb.releases.teleport.dev/teleport-pubkey.asc | sudo apt-key add -
sudo add-apt-repository 'deb https://deb.releases.teleport.dev/ stable main'
sudo apt-get update
sudo apt-get install jq net-tools -y
sudo apt-get install teleport

# teleport server config file
tee /etc/teleport.yaml <<EOF
version: v3
teleport:
  nodename: ${domain}
  data_dir: /var/lib/teleport
  log:
    output: /var/lib/teleport/teleport.log
    severity: INFO
    format:
      output: text
  ca_pin: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: ${domain}
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  labels:
    environment: prod
  enhanced_recording:
    enabled: true
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: ${domain}:443
  https_keypairs: []
  acme:
    enabled: yes
    email: ${email}
EOF

# system service file for teleport 
tee /etc/systemd/system/teleport.service <<EOF
[Unit]
Description=Teleport Server
Documentation=https://goteleport.com/docs/getting-started/linux-server/

[Service]
WorkingDirectory=/
Type=simple
ExecStart=teleport start --config=/etc/teleport.yaml --pid-file=/run/teleport.pid
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/run/teleport.pid

Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl enable teleport.service
systemctl restart teleport.service