name: Build README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Concatenate Docs into README
      run: cat docs/01-setup.md docs/02-configuration.md docs/03-troubleshooting.md docs/04-upgrades.md > README.md

    - name: Commit Updated README
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update README from docs" || echo "No changes to commit"
        git push
