#---
#apiVersion: resources.teleport.dev/v1
#kind: TeleportRoleV7
#metadata:
#  name: terraform
#spec:
#  allow:
#    app_labels:
#      '*': '*'
#    db_labels:
#      '*': '*'
#    rules:
#    - resources:
#      - app
#      - cluster_auth_preference
#      - cluster_networking_config
#      - db
#      - device
#      - github
#      - login_rule
#      - oidc
#      - okta_import_rule
#      - role
#      - saml
#      - session_recording_config
#      - token
#      - trusted_cluster
#      - user
#      verbs:
#      - list
#      - create
#      - read
#      - update
#      - delete
#---
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  name: dev-access
spec:
  allow:
    app_labels:
      'tier': ['dev']
      'aws/env': ['dev']
    aws_role_arns:
      - '{{internal.aws_role_arns}}'
    db_labels:
      'tier': ['dev']
    db_names:
    - '{{internal.db_names}}'
    - '*'
    db_roles:
    - '{{internal.db_roles}}'
    - dbadmin
    db_users:
    - '{{internal.db_users}}'
    - postgres
    - reader
    desktop_groups:
    - Administrators
    impersonate:
      users: ["Db"]
      roles: ["Db"]
    join_sessions:
    - kinds:
      - k8s
      - ssh
      modes:
      - moderator
      - observer
      name: Join dev sessions
      roles:
      - 'dev-access'
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    - system:masters
    kubernetes_labels:
      tier: dev
    kubernetes_resources:
    - kind: '*'
      name: '*'
      namespace: 'dev'
      verbs: ['*']
    logins:
    - '{{internal.logins}}'
    - '{{email.local(external.username)}}'
    - '{{email.local(external.email)}}'
    - ubuntu
    - debian
    - ec2-user
    node_labels:
      tier: dev
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - read
      - list
    windows_desktop_labels:
      tier: dev
    windows_desktop_logins:
    - '{{internal.windows_logins}}'
    - '{{email.local(external.username)}}'
    - Administrator
  options:
    create_db_user: true
    create_desktop_user: true
    create_host_user_mode: keep #https://goteleport.com/docs/enroll-resources/server-access/guides/host-user-creation/
    create_host_user_default_shell: /bin/bash
    desktop_clipboard: true
    desktop_directory_sharing: true #https://goteleport.com/docs/enroll-resources/desktop-access/directory-sharing/
    max_session_ttl: 8h0m0s
    pin_source_ip: false
---
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  name: prod-access
spec:
  allow:
    app_labels:
     - 'tier': ['prod']
     - 'aws/env': ['prod']
     - 'tier': ['dev']
     - 'aws/env': ['dev']
    aws_role_arns:
      - '{{internal.aws_role_arns}}'
    db_labels:
    - 'tier': ['prod']
    - 'tier': 'dev'
    db_names:
    - '{{internal.db_names}}'
    - '*'
    db_roles:
    - '{{internal.db_roles}}'
    - dbadmin
    db_users:
    - '{{internal.db_users}}'
    - postgres
    - reader
    - writer
    desktop_groups:
    - Administrators
    impersonate:
      users: ["Db"]
      roles: ["Db"]
    join_sessions:
    - kinds:
      - k8s
      - ssh
      modes:
      - moderator
      - observer
      name: Join prod sessions
      roles:
      - '*'
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    - system:masters
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: '*'
      name: '*'
      namespace: 'prod'
      verbs: ['*']
    logins:
    - '{{internal.logins}}'
    - '{{email.local(external.username)}}'
    - '{{email.local(external.email)}}'
    - ubuntu
    - debian
    - ec2-user
    node_labels:
    -  tier: prod
    -  tier: dev
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - read
      - list
    windows_desktop_labels:
    -  tier: ['prod', 'dev']
    windows_desktop_logins:
    - '{{internal.windows_logins}}'
    - '{{email.local(external.username)}}'
    - Administrator
  options:
    create_db_user: true
    create_desktop_user: true
    create_host_user_mode: keep #https://goteleport.com/docs/enroll-resources/server-access/guides/host-user-creation/
    create_host_user_default_shell: /bin/bash
    desktop_clipboard: true
    desktop_directory_sharing: true #https://goteleport.com/docs/enroll-resources/desktop-access/directory-sharing/
    max_session_ttl: 1h0m0s
    pin_source_ip: false
---
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  name: reviewer
spec:
  allow:
    review_requests:
      preview_as_roles:
      - access
      - prod-access
      roles:
      - access
      - prod-access
---
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  name: requester
spec:
  allow:
    request:
      roles:
      - prod-access
      search_as_roles:
      - access
      - prod-access