#!/bin/bash
#########################################################
sudo hostnamectl set-hostname ${host}
# Installs teleport enterprise edition based on https://goteleport.com/docs/server-access/getting-started/#step-14-install-teleport-on-your-linux-host
curl https://goteleport.com/static/install.sh | bash -s ${teleport_version} enterprise
#########################################################
echo ${token} > /tmp/token

cat<<EOF >/etc/teleport.yaml
version: v3
teleport:
  auth_token: /tmp/token
  proxy_server: ${proxy_service_address}:443
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
ssh_service:
  enabled: true
  labels:
    tier: dev
    os: amz-lin
  commands: #https://goteleport.com/docs/management/admin/labels/
    - name: "hostname"
      command: ["/bin/hostname"]
      period: "1m0s"
    - name: "load_average"
      command: ["/bin/sh", "-c", "cut -d' ' -f1 /proc/loadavg"]
      period: "30s"
    - name: "disk_used"
      command: ["/bin/sh", "-c", "df -hTP / | awk '{print \$6}' | egrep '^[0-9][0-9]'"]
      period: "2m0s"
proxy_service:
  enabled: false
auth_service:
  enabled: false
EOF

systemctl enable teleport
systemctl start teleport
systemctl status teleport