#!/bin/bash
#########################################################
# Installs teleport enterprise edition based on https://goteleport.com/docs/server-access/getting-started/#step-14-install-teleport-on-your-linux-host
curl https://goteleport.com/static/install.sh | bash -s ${teleport_version} enterprise
#########################################################
echo ${token} > /tmp/token

cat<<EOF >/etc/teleport.yaml
version: v3
teleport:
  auth_token: /tmp/token
  proxy_server: ${proxy_service_address}:443
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
ssh_service:
  enabled: true
  labels:
    env: dev
    os: amz-lin
proxy_service:
  enabled: false
auth_service:
  enabled: false
EOF

systemctl enable teleport;
systemctl restart teleport;